teleop_twist_joy_node:
  ros__parameters:
    joy_dev: 2
    require_enable_button: true
    inverted_reverse: true
    enable_turbo_button: -1  # R1 button for turbo mode

    enable_button: 7  # L1 button to enable
    relay_button: 3  # Button for relay control
    home_button: 11

    axis_linear:
      x: 1  # Left joystick vertical axis
    axis_angular:
      yaw: 0  # Right joystick horizontal axis
    scale_linear:
      x: 1.0
    scale_angular:
      yaw: 0.5
    enable_turbo_scale_linear:
      x: 1.0
    enable_turbo_scale_angular:
      yaw: 1.0
