global_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  width: 10.0
  height: 10.0
  resolution: 0.05
  obstacle_layer:
    enabled: true
    observation_sources: laser_scan_sensor
    laser_scan_sensor:
      topic: scan
      max_obstacle_height: 2.0
      observation_persistence: 0.0
      clearing: true
      marking: true
      data_type: LaserScan
      inf_is_valid: true
